#!/usr/bin/env bash

print_usage() {
	printf '\n%s\n' "$(basename "${0}") [-d] [-h] FILE..."
}

decrypt=""
while getopts ":dh" opt
do
    case ${opt} in
        d)
            decrypt="yes"
            ;;
        h)
            print_usage
            exit 0
            ;;
        \?)
            echo "Invalid option: -$OPTARG" 1>&2
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

if [[ ${#} -eq 0 ]]
then
    print_usage 1>&2
    exit 1
fi

# Read Password
echo -n "Password: "
read -s password1
printf "\n"

if [[ -z "${decrypt}" ]]
then
    echo -n "Confirm password: "
    read -s password2
    printf "\n"
    if [[ ! "${password1}" = "${password2}" ]]
    then
        echo "Passwords do not match!" 1>&2
        exit 1
    fi
fi

encrypt(){
    input="${1}"
    output="${input}".openssl.aes
    if [[ -f "${output}" ]]
    then
        echo "${output} exists. Skipping." 1>&2
        return 1
    fi
    openssl aes-256-cbc -a -pbkdf2 -salt -in "${input}" -out "${output}" \
        -pass file:<( echo -n "${password1}" )
    if [[ ! ${?} -eq 0 ]]
    then
        rm "${output}"
    fi
}

decrypt(){
    input="${1}"
    output="${input%.openssl.aes}"
    if [[ "${input}" = "${output}" ]]
    then
        echo "Files must end in << .openssl.aes >>." 1>&2
        return 1
    fi
    if [[ -f "${output}" ]]
    then
        echo "${output} exists. Skipping." 1>&2
        return 1
    fi
    openssl aes-256-cbc -a -pbkdf2 -d -in "${input}" -out "${output}" \
        -pass file:<( echo -n "${password1}" )
    if [[ ! ${?} -eq 0 ]]
    then
        rm "${output}"
    fi
}

if [[ -z "${decrypt}" ]]
then
    for arg in "${@}"
    do
        encrypt "${arg}"
    done
    exit 0
fi

for arg in "${@}"
do
    decrypt "${arg}"
done
