#!/bin/bash

print_usage() {
	printf '\n%s\n' "$(basename "${0}") [-d] FILE..."
}

decrypt=""
while getopts ":di:" opt
do
    case ${opt} in
        d)
            decrypt="yes"
            ;;
        h)
            print_usage
            exit 0
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2 
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

if [[ ${#} -eq 0 ]]
then
    print_usage 1>&2
    exit 1
fi

# Read Password
echo -n Password: 
read -s password1
echo
echo -n Confirm password: 
read -s password2
echo

if [[ ! "${password1}" = "${password2}" ]]
then
    echo 'Passwords do not match!' 1>&2
    exit 1
fi

encrypt(){
    input="${1}"
    output="${input}".openssl.aes
    if [[ -f "${output}" ]]
    then
        printf '%s exists.' "${output}" 1>&2
        exit 1
    fi
    openssl aes-256-cbc -a -pbkdf2 -salt -in "${input}" -out "${output}" \
        -pass file:<( echo -n "${password1}" )
}

decrypt(){
    input="${1}"
    output="${input%.openssl.aes}"
    if [[ -f "${output}" ]]
    then
        printf '%s exists.\n' "${output}" 1>&2
        exit 1
    fi
    openssl aes-256-cbc -a -pbkdf2 -d -in "${input}" -out "${output}" \
        -pass file:<( echo -n "${password1}" )
}

if [[ -z "${decrypt}" ]]
then
    for arg in "${@}"
    do
        encrypt "${arg}"
    done
    exit 0
fi

for arg in "${@}"
do
    decrypt "${arg}"
done
