#!/usr/bin/env bash

# set -x

print_usage() {
	printf '\n%s\n' "$(basename "${0}") FILE..."
}

if [[ ${#} -lt 1 ]]
then
    print_usage 1>&2
    exit 1
fi

for arg in "${@}"
do
    if [[ ! -f "${arg}" ]]
    then
        printf '%s is not a file.\n' "${arg}" 1>&2
        exit 1
    fi
done

if [[ ${#} -eq 1 ]]
then
    file="${1}"
    outdir="$(dirname "${file}")"
    libreoffice --convert-to xlsx --infilter=csv:44,34,76 --outdir "${outdir}" "${file}"
    exit
fi

# 76 is the number of the UTF-8 encoding (and 44 the comma and 34 the double
# quote character ASCII value)
# Source {{{
# https://ask.libreoffice.org/en/question/144942/how-to-convert-to-csv-with-utf-8-encoding-using-lo5-command-line
# }}}

libreoffice --convert-to xlsx --infilter=csv:44,34,76 "${@}"

# vim: foldmethod=marker
