#!/usr/bin/env bash

# set -x

print_usage() {
	printf '\n%s\n' "$(basename "${0}") [DIR]"
}

vim_bundle(){
    find "${1}" ! -path \*/.\* ! -path ./pack/\* \
        ! -path ./eclim/\* ! -path ./swap/\* ! -path ./backup/\* \
        ! -name \*.sw\* \
        -type f
}

eclipse_project(){
find "${1}" ! -path ./.\* ! -path ./classes/\* ! -path ./build/\* \
    ! -path ./dumps/\* ! -path ./bin/\* ! -path ./test-classes/\* \
    ! -path ./target/\* ! -iname \*.class ! -iname \*.jasper \
    -type f
}

dir="."

if [[ ! ${#} -le 1  ]]
then
    print_usage >&2
    exit 1
fi

if [[ -n "${1}" ]]
then
    dir="${1}"
fi

find "${dir}" ! -path \*/.\* ! -path \*
    -type f

if [[ -f ./init.vim ]]
then
    vim_bundle "${dir}"
    exit 0
fi

if [[ -f ./.project ]]
then
    eclipse_project "${dir}"
    exit 0
fi

find "${dir}" ! -path \*/.\* -type f
