#!/usr/bin/env bash

# set -x

print_usage() {
	printf '\n%s\n' "$(basename "${0}") [-C] [-c CACHE_DIR] [DIR]"
}

clear_cache=""
cache_dir=~/.cache/fzf_cache
while getopts ":hCc:" opt
do
    case ${opt} in
        h)
            print_usage
            exit
            ;;
        C)
            clear_cache="true"
            ;;
        c)
            cache_dir="${OPTARG}"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

if [[ ! ${#} -le 1  ]]
then
    print_usage >&2
    exit 1
fi

list_files(){
    find "${1}" ! -path \*/.\* -type f \
        ! -iname \*.o \
        ! -iname \*.lo \
        ! -iname \*.elc \
        ! -iname \*.fasl \
        ! -iname \*.class \
        ! -iname \*.exe \
        ! -iname \*.bin
}

dir="."
[[ -n "${1}" ]] && dir="${1}"

[[ ! -d "${cache_dir}"  ]] && mkdir -p "${cache_dir}"

cache_file="${cache_dir}/$(printf $(readlink -f "${dir}") | base64)"

if [[ -n "${clear_cache}" && -f "${cache_file}" ]]
then
    rm "${cache_file}"
fi

if [[ ! -f "${cache_file}" ]]
then
    if [[ -z "${DFZF_DEFAULT_COMMAND}" ]] || \
        ! ${DFZF_DEFAULT_COMMAND} "${dir}" > "${cache_file}"
    then
        list_files "${dir}" > "${cache_file}"
    fi
fi

cat "${cache_file}"
