#!/usr/bin/env bash

# set -x

hash rg &>/dev/null || { echo "Ripgrep required." >&2 && exit 1; }

print_usage() {
	printf '\n%s\n' "$(basename "${0}") [-C] [-c CACHE_DIR] [DIR]"
}

clear_cache=""
cache_dir=~/.cache/find_file_cache
while getopts ":hCc:" opt
do
    case ${opt} in
        C)
            clear_cache="true"
            ;;
        c)
            cache_dir="${OPTARG}"
            ;;
        h)
            print_usage
            exit
            ;;
    esac
done
shift $((OPTIND - 1))

if [[ ! ${#} -le 1  ]]; then
    print_usage >&2
    exit 1
fi

dir="."
[[ -n "${1}" ]] && dir="${1}"

[[ ! -d "${cache_dir}"  ]] && mkdir -p "${cache_dir}"
cache_file="${cache_dir}/$(printf $(readlink -f "${dir}") | base64)"
[[ -n "${clear_cache}" && -f "${cache_file}" ]] && rm "${cache_file}"

if [[ ! -f "${cache_file}" ]]; then
    rg --files "${dir}" | sort > "${cache_file}"
fi

cat "${cache_file}"
