#!/usr/bin/env bash

# set -x

print_usage() {
    printf '\nUsage:\n\n\t%s\n' "$(basename "${0}") (update|recreate|get_files)"
}

if [[ ! ${#} -eq 1  ]]
then
    print_usage >&2
    exit 1
fi

fplay_database=~/.cache/fplay_database.db

purge_database(){
    if [[ -f "${fplay_database}" ]]
    then
        rm "${fplay_database}"
    fi
}

import_last_acess(){
    last_access="$(mktemp)"
    find . -mindepth 1 -maxdepth 1 ! -path \*/.\* -type f -printf '%T@\t%p\n' \
        > "${last_access}"
    sqlite3 -batch "${fplay_database}" <<EOF
CREATE TEMPORARY TABLE media_last_access_temp(
timestamp DOUBLE PRECISION,
name TEXT
);
.separator "\t"
.import "${last_access}" media_last_access_temp
insert or ignore into media_last_access
SELECT * from media_last_access_temp;
EOF
    rm "${last_access}"
}

import_mime_type(){
    mime_type="$(mktemp)"
    find . -mindepth 1 -maxdepth 1 ! -path \*/.\* -type f -exec file -i -F '	' "{}" \+ \
        > "${mime_type}"
    sqlite3 -batch "${fplay_database}" <<EOF
CREATE TEMPORARY TABLE media_mime_type_temp(
name TEXT,
mime_type TEXT
);
.separator "\t"
.import "${mime_type}" media_mime_type_temp
insert or ignore into media_mime_type
SELECT * from media_mime_type_temp;
EOF
    rm "${mime_type}"
}

create_database(){
    if [[ ! -d ~/.cache ]]
    then
        mkdir ~/.cache
    fi
    if [[ ! -f "${fplay_database}" ]]
    then
        sqlite3 -batch "${fplay_database}" <<EOF
CREATE TABLE media_last_access(
timestamp DOUBLE PRECISION,
name TEXT PRIMARY KEY
);
CREATE TABLE media_mime_type(
name TEXT PRIMARY KEY,
mime_type TEXT
);
CREATE INDEX ix_last_access_timestamp ON media_last_access(timestamp);
CREATE INDEX ix_last_access_name ON media_last_access(name);
CREATE INDEX ix_mime_type_name ON media_mime_type(name);
EOF
    fi
}

update(){
    create_database
    import_last_acess
    import_mime_type
}

recreate(){
    purge_database
    update
}

get_files(){
    sqlite3 "${fplay_database}" \
        "SELECT t.name \
        from media_mime_type t \
        join media_last_access l \
            on l.name = t.name \
        where mime_type like '%video%' \
        or mime_type like '%audio%' \
        order by timestamp desc;"
}

cmd="${1}"

case ${cmd} in
    update)
        update
        ;;
    get_files)
        get_files
        ;;
    recreate)
        recreate
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2 
        exit 1
        ;;
esac
