#!/bin/sh

script_name="$(basename "${0}")"

exec_command(){
    "${@}" 2>&1 | tee "${stdouterr_file}"
}

sil_exec_command(){
    "${@}" > "${stdout_file}" 2>"${stderr_file}"
    err_code=${?}
    if [ ${err_code} -gt 1 ]
    then
        printf '\n%s\n\n' "${target}"
        printf '\n%s\n' '------------------------------------------------'
        cat "${stderr_file}"
        return 1
    fi
    : > "${stderr_file}"
    return 0
}

conf_file="./${script_name}".conf

if [ ! -f "${conf_file}" ]
then
	printf '%s not a file.\n' "${conf_file}"
	exit 1
fi

. "${conf_file}"

stderr_file=$(mktemp --suffix="_${script_name}.error")

cd "${base_dir}"

for target in ${folders}
do

    if [ ! -d "${target}" ]
    then
        printf 'Skipping %s: not a directory.\n' "${target}"
        continue
    fi

    printf '\n%s\n\n' "${target}"

    stdout_file="${log_dir}/${script_name}_${target}_${comment}"
    stdouterr_file="${log_dir}/${script_name}_${target}_`date +'%Y%m%d%H%M%S'`"

    if ! touch "${stdouterr_file}"
    then
        exit 1
    fi

    cd "${target}"

    sil_exec_command git checkout master \
        ; exec_command git push

	cd "${base_dir}"

    printf '\n%s\n' '------------------------------------------------'
done
