#!/usr/bin/env bash

script_name="$(basename "${0}")"

get_git_branch(){
    git branch | grep \* | cut -d ' ' -f2
}

conf_file="./${script_name}".conf

if [[ ! -f "${conf_file}" ]]
then
	printf '%s not a file.\n' >&2 "${conf_file}"
	exit 1
fi

. "${conf_file}"

cd "${base_dir}"

for target in ${folders}
do

    if [[ ! -d "${target}" ]]
    then
        printf 'Skipping %s: not a directory.\n' "${target}"
        continue
    fi

    printf '\n%s\n\n' "${target}"

    log_file="${log_dir}/${script_name}_${target}_`date +'%Y%m%d%H%M%S'`"

    if ! touch "${log_file}"
    then
        exit 1
    fi

    cd "${target}"

    current_branch=$(get_git_branch)

    if [[ ${current_branch} = "master" ]]
    then
        git push 2>&1 | tee "${log_file}"
    else
        printf '\033[0;31m%s not in master branch.\n\033[0m' "${target}" >&2
    fi

	cd "${base_dir}"

    printf '\n%s\n' '------------------------------------------------'
done
