#!/usr/bin/env bash

# set -x
# echo "${@}"

print_usage() {
    echo -e "\n$(basename $0) OLD HIS MINE MERGED"
}

if [[ ! ${#} -eq 4 ]]
then
	print_usage 1>&2
	exit 1
fi

old="${1}"
his="${2}"
mine="${3}"
merged="${4}"

vim=/usr/bin/vim

if [[ "${EDITOR}" != "${EDITOR%%vim}" ]]
then
    vim="${EDITOR}"
    echo -e "Editor is: ${vim}\n"
fi

${vim} -d "${mine}" "${old}" "${his}" "${merged}" \
    -c "exec bufwinnr(4) . 'wincmd w' | wincmd J" \
    -c "silent set modifiable | diffoff | setlocal scrollbind cursorbind"
