#!/usr/bin/env bash

# set -x

if [[ -z "${FPLAY_PLAYER}" ]]
then
    printf 'FPLAY_PLAYER not set.\n' 1>&2
    exit 1
fi

print_usage() {
	printf '\n%s\n' "$(basename "${0}") [DIR]"
}

if [[ ! ${#} -le 1 ]]
then
    print_usage 1>&2
    exit 1
fi

dir="."

if [[ -n "${1}" ]]
then
    dir="${1}"
fi

if [[ ! -d "${dir}" ]]
then
    printf '%s is not a directory.\n' "${dir}" 1>&2
    exit 1
fi

selectfile(){
    list_video_files "${dir}" | fzf
}

file="`selectfile`"

err=${?}

if [[ ! ${err} -eq 0 ]]
then
    printf 'Aborted.\n' 1>&2
    exit 1
fi

evaluated=$(eval echo "${FPLAY_PLAYER}")

if [[ "${FPLAY_PLAYER}" == "${evaluated}" ]]
then
    FPLAY_PLAYER=( ${FPLAY_PLAYER} )
else
    FPLAY_PLAYER="${evaluated}"
fi

printf 'Playing %s.\n' "${file}"

if [[ -n "${FPLAY_BACKGROUND}" ]]
then
    "${FPLAY_PLAYER[@]}" "${file}" >/dev/null 2>&1 &
    exit $?
fi

"${FPLAY_PLAYER[@]}" "${file}"
