#!/usr/bin/env bash

set -e
# set -x

get_timestamp(){
  stat -c '%y' "${1}"
}

program="${0##*/}"

print_usage() {
    echo "${program} [-h]

    Install/Update Neovim from https://github.com/neovim/neovim/releases/.

    -h            show this help message and exit

    Currently only 'nightly' is supported."
}

while getopts :h opt
do
  case ${opt} in
    h)
      print_usage
      exit
      ;;
    \?)
      echo "Invalid option: -${OPTARG}" >&2
      print_usage >&2
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

folder="/tmp/$(echo "${program}" | base64)"

[[ -d "${folder}" ]] || mkdir "${folder}"

file="${folder}/nvim-linux-x86_64.tar.gz"

zflag=()

[[ -e "${file}" ]] && zflag=(-z "${file}")

curl -LR "${zflag[@]}" -o "${file}" \
  https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz

[[ -e /opt/nvim-linux-x86_64/bin/nvim ]] && before="$(get_timestamp /opt/nvim-linux-x86_64/bin/nvim)"
[[ -n "${before}" ]] && tar -C "${folder}" -xf "${file}" nvim-linux-x86_64/bin/nvim && \
  after="$(cd "${folder}" && get_timestamp nvim-linux-x86_64/bin/nvim)"

[[ -n "${before}" ]] && [[ "${before}" >= "${after}" ]] && exit

[[ -n "${before}" ]] && before="${folder}/before" && \
  (cd /opt && rg --files nvim-linux-x86_64/) | sort > ${before}

sudo tar -C /opt -xf "${file}"

[[ -z "${before}" ]] && exit

after="${folder}/after" && tar -tf "${file}" | rg -v '/$' | sort > ${after}
except="${folder}/except" && comm -2 -3 ${before} ${after} > ${except}

[[ -s ${except} ]] || exit

echo -e "\nThese files were found in excess:\n"
cat ${except}
echo

read -p "About to delete above files. Are you sure? " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]
then
  (cd /opt && sudo -k xargs -t -d'\n' rm < ${except})
fi
