#!/usr/bin/env bash

set -e
# set -x

get_timestamp(){
  stat -c '%y' "${1}"
}

tempname(){
  mktemp -p "${folder}" --suffix=_"${1}" -u
}

folder="/tmp/$(basename "${0}" | base64)"

[[ -d "${folder}" ]] || mkdir "${folder}"

file="${folder}/nvim-linux-x86_64.tar.gz"

zflag=()

[[ -e "${file}" ]] && zflag=(-z "${file}")

curl -LR "${zflag[@]}" -o "${file}" \
  https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz

[[ -e /opt/nvim-linux-x86_64/bin/nvim ]] && before="$(get_timestamp /opt/nvim-linux-x86_64/bin/nvim)"
after="$(get_timestamp "${file}")"

[[ "${before}" == "${after}" ]] && exit

[[ -n "${before}" ]] && before=$(tempname before) && \
  (cd /opt && rg --files nvim-linux-x86_64/) | sort > ${before}

sudo tar -C /opt -xf "${file}"

[[ -z "${before}" ]] && exit

after=$(tempname after) && tar -tf "${file}" | rg -v '/$' | sort > ${after}
except=$(tempname except) && comm -2 -3 ${before} ${after} > ${except}

[[ -s ${except} ]] || exit

echo -e "\nThese files were found in excess:\n"
cat ${except}
echo

read -p "About to delete. Are you sure? " -n 1 -r
echo # move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  (cd /opt && xargs -t -d'\n' sudo -k rm < ${except})
fi
