#!/bin/sh

tmpdir="$(dirname "$(mktemp -u)")"
# script_name="$(basename "${0}")"
# log_file=$(mktemp --suffix="_${script_name}.log")

echo "let nomod_cur_bufnr = bufnr('%') | \
    noautocmd argdo \
    if expand('%:p') =~# '^\\V' . '${tmpdir}' | \
        setlocal nomodifiable | \
    endif | \
    exec 'b ' . nomod_cur_bufnr | \
    exec 'normal! gg' | visual" |  nvim -e "${@}"
