#!/bin/sh

# set -x

for arg in "${@}"
do
    if [ "${arg}" = "/dev/null" ]
    then
        echo "One of the arguments is /dev/null. Skipping." 1>&2
        exit 1
    fi
done

tmpdir="$(dirname "$(mktemp -u)")"

vim --cmd "autocmd VimEnter * noautocmd windo \
    if expand('%:p') =~# '^\\V' . '${tmpdir}' | \
        setlocal nomodifiable | endif" "${@}"
