#!/bin/sh

# set -x

case "${EDITOR}" in
    *vim)
        ;;
    "")
        echo '$EDITOR not set.' >&2
        exit 1
        ;;
    \?)
        echo "Editor '${EDITOR}' not supported." >&2
        exit 1
        ;;
esac

for arg in "${@}"
do
    if [ "${arg}" = "/dev/null" ]
    then
        echo "One of the arguments is /dev/null. Skipping." 1>&2
        exit 1
    fi
done

tmpdir="$(dirname "$(mktemp -u)")"

"${EDITOR}" --cmd "autocmd VimEnter * noautocmd windo \
    if expand('%:p') =~# '^\\V' . '${tmpdir}' | \
        setlocal nomodifiable | endif" "${@}"
