#!/usr/bin/env bash

# set -x

ipc_server_folder="/tmp/9572cf67-b586-4c68-a7da-7cb904b396b3"
words=~/.local/share/dict/words

[[ -d "${ipc_server_folder}" ]] || mkdir "${ipc_server_folder}"

next_available_name()(
  # https://stackoverflow.com/a/34985567 "locally scoped" function
  is_name_available(){
    s="${ipc_server_folder}/${1}"
    if test -e "${s}"  && lsof "${s}" 2>&1 >/dev/null; then
      return 1
    fi
  }

  set_main(){
    m="${ipc_server_folder}/main"
    [[ ! -e "${m}" ]] && touch "${m}"
    s="${ipc_server_folder}/${1}"
    if ! lsof "$(readlink -f "${m}")" 2>&1 >/dev/null; then
      ln -sf "${s}" "${m}"
    fi
  }

  if test -n "${1}" && is_name_available ${1}; then
    set_main ${1}
    echo ${1}
    return
  fi

  lc=$(wc -l < "${words}")
  for (( i = 1; i <= ${lc}; i++ )); do
    w=$(sed -n ${i}p "${words}")
    if is_name_available ${w}; then
      set_main ${w}
      echo ${w}
      return
    fi
  done
)

name=""
socket=()

if test ${#} -eq 1 && test "${1##*.}" = "m3u"; then
  name="${1%.*}"
  socket=(--input-ipc-server="${ipc_server_folder}/${name}")
fi

while getopts :hs: opt
do
  case ${opt} in
    h)
      program="${0##*/}"
      echo "${program} [-h] -s IPC_SOCKET_ALIAS (see 'control -h')"
      exit
      ;;
    s)
      name=${OPTARG}
      ;;
  esac
done
shift $((OPTIND - 1))

mpv=(mpv --msg-level=all=no --terminal=no --playlist-start=0)

if [[ -z "${socket[@]}" && -f "${words}" ]]; then
  name=$(next_available_name ${name})

  if [[ -n ${name} ]]; then
    socket=(--input-ipc-server="${ipc_server_folder}/${name}")
  fi
fi

if [[ -n "${socket[@]}" ]]; then
  mpv+=(--title="[${name}] \${filename}" "${socket[@]}")
fi

if [[ ${#} -eq 0  ]]; then
  <&0 xargs -d'\n' setsid -f "${mpv[@]}"
  exit
fi

if [[ "${!#}" == "-" ]]; then
  <&0 xargs -d'\n' setsid -f "${mpv[@]}" "${@:1:$#-1}" # drop the last parameter
  exit
fi

setsid -f "${mpv[@]}" "${@}"
