#!/usr/bin/env bash

# set -x

ipc_server_folder="/var/tmp/9572cf67-b586-4c68-a7da-7cb904b396b3"
words=~/.local/share/dict/words

[[ -d "${ipc_server_folder}" ]] || mkdir "${ipc_server_folder}"

next_available_name(){
  lc=$(wc -l < "${words}")
  for (( i = 1; i <= ${lc}; i++ )); do
    w=$(sed -n ${i}p "${words}")
    s="${ipc_server_folder}/${w}"
    if test ! -e "${s}"  || ! lsof "${s}" 2>&1 >/dev/null; then
      echo "${w}"
      return
    fi
  done
}

socket=()
while getopts :hs: opt
do
  case ${opt} in
    h)
      program="${0##*/}"
      echo "${program} [-h] -s IPC_SOCKET_ALIAS (see 'control -h')"
      exit
      ;;
    s)
      name=${OPTARG}
      socket=(--input-ipc-server="${ipc_server_folder}/${OPTARG}")
      ;;
  esac
done
shift $((OPTIND - 1))

mpv=(mpv --msg-level=all=no --terminal=no --playlist-start=0)

if [[ -z "${socket[@]}" && -f "${words}" ]]; then
  name=$(next_available_name)

  if [[ -n ${name} ]]; then
    socket=(--input-ipc-server="${ipc_server_folder}/${name}")
  fi
fi

if [[ -n "${socket[@]}" ]]; then
  mpv+=(--title="[${name}] \${filename}" "${socket[@]}")
fi

if [[ ${#} -eq 0  ]]; then
  <&0 xargs -d'\n' setsid -f "${mpv[@]}"
  exit
fi

if [[ "${!#}" == "-" ]]; then
  <&0 xargs -d'\n' setsid -f "${mpv[@]}" "${@:1:$#-1}" # drop the last parameter
  exit
fi

setsid -f "${mpv[@]}" "${@}"
