#!/usr/bin/env bash

# set -x

program="${0##*/}"

print_usage() {
    echo "${program} [-P|-h]

    Query files (specialized in media files and M3U playlists).

    -P            DO NOT exclude M3U playlists (they are excluded by default)
    -h            show this help message and exit

    Prefix (.prefix) files are excluded."
}

exclude=(! -name "*.prefix" ! -name "*.m3u" ! -name "*.m3u.*")
while getopts :Ph opt
do
  case ${opt} in
    P)
      exclude=(! -name "*.prefix")
      ;;
    h)
      print_usage
      exit
      ;;
    \?)
      echo "Invalid option: -${OPTARG}" >&2
      print_usage >&2
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

terms=()

while [[ ${#} -gt 0 ]]; do
  case "${1}" in
    --)
      shift  # Remove -- from the argument list
      break
      ;;
    *)
      terms+=("${1}")
      shift
      ;;
  esac
done

if [[ ${#terms[@]} -eq 0 || ${#terms[@]} -gt 4 ]]; then
	echo "1 to 4 arguments" >&2
	exit 1
fi

files(){
  find -L . ! -path \*/.\* -type f "${exclude[@]}"
}

r0(){
  rg -F -i -e "${terms[0]}" "${@}"
}

if [[ ${#} -eq 0 ]]; then
  r1(){
    files | r0
  }
else
  r1(){
    r0 "${@}"
  }
fi

if [[ ${#terms[@]} -eq 1 ]]; then
  r0(){
    rg --sort path -F -i -e "${terms[0]}" "${@}"
  }
  r1 "${@}"
  exit 0
fi

r9(){
  rg --sort path -F -i -e "${1}"
}

if [[ ${#terms[@]} -eq 2 ]]; then
  r1 "${@}" | r9 "${terms[1]}"
  exit 0
fi

r2(){
  rg -F -i -e "${1}"
}

if [[ ${#terms[@]} -eq 3 ]]; then
  r1 "${@}" | r2 "${terms[1]}" | r9 "${terms[2]}"
  exit 0
fi

r1 "${@}" | r2 "${terms[1]}" | r2 "${terms[2]}" | r9 "${terms[3]}"
