#!/usr/bin/env bash

set -x

program="${0##*/}"

print_usage() {
    echo "${program} [-P|-h]

    Query files (performant, specialized in media files and M3U playlists).

    -Y            Exclude youtube-dl control files
    -h            show this help message and exit
    -p            DO NOT exclude M3U playlists (they are excluded by default)

    Prefix (.prefix) files are excluded."
}

playlist=(! -name "*.m3u")
ytdl=()
while getopts :Yhp opt
do
  case ${opt} in
    Y)
      ytdl=(! -name "*.part" ! -name "*.ytdl")
      ;;
    h)
      print_usage
      exit
      ;;
    p)
      playlist=()
      ;;
    \?)
      echo "Invalid option: -${OPTARG}" >&2
      print_usage >&2
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))
if [[ ${#} -eq 0 || ${#} -gt 4 ]]; then
	echo "1 to 4 arguments" >&2
	exit 1
fi

files(){
  find -L . ! -path \*/.\* -type f "${exclude[@]}"
}

exclude=("${playlist[@]}" "${ytdl[@]}")

if [[ ${#} -eq 1 ]]; then
  files | rg --sort path -F -i -e "${1}"
  exit 0
fi

if [[ ${#} -eq 2 ]]; then
  files | rg --color always -F -i -e "${1}" | rg --sort path -F -i -e "${2}"
  exit 0
fi

if [[ ${#} -eq 3 ]]; then
  files | rg --color always -F -i -e "${1}" | rg --color always -F -i -e "${2}" | \
    rg --sort path -F -i -e "${3}"
  exit 0
fi

files | rg --color always -F -i -e "${1}" | rg --color always -F -i -e "${2}" | \
  rg --color always -F -i -e "${3}" | rg --sort path -F -i -e "${4}"
