#!/usr/bin/env bash

set -x

print_usage() {
	printf '\n%s\n' "$(basename $0) FILE..."
}

if [[ ! ${#} -gt 0 ]]
then
    print_usage
    exit 1
fi

while [[ -n "${1}" ]]
do
    file="${1}"
    extension="${file##*.}"
    directory="${file%/*}"
    name="${file##*/}"
    name_wo_extension="${name%.*}"

    shift

    if [[ ! "${extension}" = "mp3" ]] && [[ ! "${extension}" = "m4a" ]] \
        && [[ ! "${extension}" = "ogg" ]]
    then
        printf 'Format "%s" not supported. Skipping.\n' "${extension}" 1>&2
        continue
    fi

    wav=`mktemp --suffix=.wav -p "${PWD}"`
    vaw=`mktemp --suffix=.wav -p "${PWD}"`

    ffmpeg -y -i "${file}" "${wav}"
    sox "${wav}" "${vaw}" reverse

    reverse="`reverse-string "${name_wo_extension}"`"

    full_reverse=${reverse}

    if [[ ! "${file}" = "${directory}" ]]
    then
        full_reverse="${directory}/${reverse}"
    fi

    if [[ "${extension}" = "mp3" ]]
    then
        ffmpeg -y -i "${vaw}" -vn -acodec libmp3lame -ab 128k "${full_reverse}.mp3"
    fi

    if [[ "${extension}" = "m4a" ]]
    then
        ffmpeg -y -i "${vaw}" -vn -acodec aac -ab 128k "${full_reverse}.m4a"
    fi

    if [[ "${extension}" = "ogg" ]]
    then
        ffmpeg -y -i "${vaw}" -vn -acodec libvorbis -qscale:a 5 "${full_reverse}.ogg"
    fi

    rm "${wav}" "${vaw}"
done
