#!/usr/bin/env python3

import sys
import os

script = sys.argv[0]
args = sys.argv[1:]

def usage():
    return "%s STRING\n" % os.path.basename(script)

if len(args) != 1:
    sys.stdout.write(usage())
    sys.exit(1)

string = args[0]

print(string[::-1])
