#!/usr/bin/env bash

# Restore tmux session after reboot
# https://superuser.com/a/615716

# Save and restore the state of tmux sessions and windows.
#
# TODO: persist and restore the state & position of panes.
set -e
set -x

dump() {
  local d=$'\t'
  tmux list-panes -a -F "\
#{automatic-rename}${d}#S${d}#W${d}\
#{pane_at_top}#{pane_at_left}#{pane_at_bottom}#{pane_at_right}\
${d}#{pane_current_path}"
}

save() {
  echo "WARNING! Script in development. Session saved to “~/.tmux-session.test”."
  dump > ~/.tmux-session.test # TODO test
}

terminal_size() {
  stty size 2>/dev/null | awk '{ printf "-x%d -y%d", $2, $1 }'
}

session_exists() {
  tmux has-session -t "$1" 2>/dev/null
}

add_window() {
  tmux new-window -t "$1:" -n "$2" -c "$3"
}

split_window() {
  tmux split-window -c "${1}"
}

new_session() {
  cd "$3" &&
  tmux new-session -d -s "$1" -n "$2" $4
}

automatic_rename() {
  [[ ${1} -eq 1 ]] && tmux setw -t ${2} automatic-rename on
}

restore() {
  tmux start-server
  local count=0
  local window_number
  local dimensions="$(terminal_size)"

  while IFS=$'\t' read automatic_rename session_name window_name facts path; do
    if [[ -d "$path" && $window_name != "log" && $window_name != "man" ]]; then
      if session_exists "$session_name"; then
        if [[ "${current_window}" == "${window_name}" && "${facts}" != 1111 ]]; then
          split_window "${path}"
        else
          add_window "$session_name" "$window_name" "$path"
          current_window="${window_name}"
          window_number=$(( window_number + 1 ))
          automatic_rename ${automatic_rename} ${window_number}
        fi
      else
        new_session "$session_name" "$window_name" "$path" "$dimensions"
        count=$(( count + 1 ))
        window_number=0
        automatic_rename ${automatic_rename} ${window_number}
      fi
    fi
  done < ~/.tmux-session.test # TODO test

  echo "restored $count session(s)"
}

case "$1" in
save | restore )
  $1
  ;;
* )
  echo "valid commands: save, restore" >&2
  exit 1
esac
