#!/usr/bin/env bash

print_usage() {
	printf '\n%s\n' "$(basename "${0}") [DIR]"
}

dir="."

if [[ ! ${#} -le 1  ]]
then
    print_usage >&2
    exit 1
fi

if [[ -n "${1}" ]]
then
    dir="${1}"
fi

find "${dir}" ! -path \*/.\* ! -path \*/classes/\* ! -path \*/build/\* \
    ! -path \*/dumps/\* ! -path \*/bin/\* ! -path \*/test-classes/\* \
    ! -path \*/target/\* ! -path \*/node_modules/\* ! -path \*/compiled/\* \
    ! -iname \*.class ! -iname \*.jasper \
    -type f
